[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "wheel",
    "ninja",
    "cmake",
    "mypy",
    "pytest",
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "_version.py"
root = "../.."

[project]
name = "pyjerrycan"
dynamic = ["version"]
description = "API for interfacing auto-trainer hardware modules."
license = { text = "AGPL-3.0-only" }
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
