CONFIG_LOG=y
CONFIG_SHELL=y
CONFIG_CONSOLE=y

CONFIG_PM=n
CONFIG_PM_DEVICE=n

CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_IMG_MANAGER=y

# Flash driver to store firmware image
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_STREAM_FLASH=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
CONFIG_SPI_NOR_SFDP_RUNTIME=y
CONFIG_IMG_MANAGER=y

CONFIG_INPUT=y
CONFIG_INPUT_EVENT_DUMP=y

CONFIG_LIB_MOTOR_MOTION=y

CONFIG_LIB_JERRYCAN=y

CONFIG_DEBUG=y
CONFIG_DMA_LOG_LEVEL_DBG=y

# This is useful for debugging, but not recommended for production
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_USE_LOG=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=30
# CONFIG_THREAD_NAME=y

CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_RUNTIME=y
CONFIG_SETTINGS_NVS=y
CONFIG_SETTINGS_SHELL=y

CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0100
CONFIG_USB_DEVICE_MANUFACTURER="ZEPHYR"
CONFIG_USB_DEVICE_PRODUCT="USB-DEV"
CONFIG_USB_DEVICE_SN="0123456789ABCDEF"
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

CONFIG_USB_CDC_ACM=y
