CONFIG_LOG=y
#CONFIG_SHELL=y
CONFIG_CONSOLE=y

CONFIG_PM=n
CONFIG_PM_DEVICE=n

CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_IMG_MANAGER=y

# Flash driver to store firmware image
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_STREAM_FLASH=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
CONFIG_SPI_NOR_SFDP_RUNTIME=y
CONFIG_IMG_MANAGER=y

CONFIG_INPUT=y
CONFIG_INPUT_EVENT_DUMP=y

CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_LIB_MOTOR_MOTION=y

CONFIG_DEBUG=y
CONFIG_DMA_LOG_LEVEL_DBG=y

CONFIG_THREAD_ANALYZER=n
CONFIG_THREAD_ANALYZER_USE_LOG=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=30
CONFIG_THREAD_NAME=y

CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y

CONFIG_I2C=y

CONFIG_SENSOR=y
#CONFIG_SENSOR_SHELL=y

CONFIG_LIB_FFT=y
#CONFIG_LIB_FFT_SHELL=y

CONFIG_LIB_MIC=y
#CONFIG_LIB_MIC_SHELL=y
