# Configuration options for MCUBoot
CONFIG_MCUBOOT_LOG_LEVEL_DBG=n
CONFIG_DEBUG=n

CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
CONFIG_BOOT_SWAP_USING_SCRATCH=y

CONFIG_BOOT_MAX_IMG_SECTORS=256

CONFIG_LL_SERVO=n
CONFIG_LIB_MIC=n
CONFIG_LL_LOAD_CELL=n
CONFIG_LL_PRESSURE_SENSOR=n
CONFIG_LL_GENERIC_GPIO=n
CONFIG_LIB_JERRYCAN=n