[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "WhiskerWire"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.10"
keywords = []
dependencies = [
    "textual==0.79.1",
    "pyjerrycan",
    "JSON-minify==0.3.0",
    "textual-plotext==0.2.1",
    "click==8.1.7",
]

[tool.hatch.build.hooks.vcs]
version-file = "whiskerwire/__about__.py"

[tool.hatch.version]
source = "vcs"
raw-options = { root = "../.."}

[project.scripts]
whiskerwire = "whiskerwire.entry_points:whiskerwire_app"

[tool.hatch.envs.types]
extra-dependencies = [
    "mypy>=1.0.0",
]
